### ISSUE TITLE
CUDA capability sm_120

### ISSUE THREAD

**Issue by soosp** [lmoe/wyoming-xtts#1]
I tried to run this container, but got a warning:
```
/opt/venv/lib/python3.11/site-packages/torch/cuda/__init__.py:287: UserWarning:
NVIDIA GeForce RTX 5060 Ti with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA GeForce RTX 5060 Ti GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
```

**Comment by lmoe** [comment]
@soosp Hey, thanks for raising the issue. Can you try the `lmo3/wyoming-xtts:cu128` build I just pushed to Dockerhub?

**Comment by soosp** [comment]
Hi, Thanks for the quick fix! It is works now.

**Comment by lmoe** [comment]
Awesome, thanks for testing. :)
